#include<stdio.h>
#include<conio.h>
void main()




{


	clrscr();


	float a,b,sum,difference,product,quotient;

	printf("ENTER THE VALUE OF a");
	scanf("%f",&a);

	printf("ENTER THE VALUE OF b");
	scanf("%f",&b);

	sum=a+b;
	difference=a-b;
	product=a*b;
	quotient=a/b;

	printf("\nSUM OF NUMBERS=%f",sum);
	printf("\nDIFFERENCE OF NUMBERS=%f",difference);
	printf("\nPRODUCT OF NUMBERS=%f",product);
	printf("\nQUOTIENT OF NUMBERS=%f",quotient);



	getch();





}