#include<stdio.h>
#include<conio.h>
void main()

{
	int p,n;
	float r,si;
	clrscr();
      /*	printf("ENTER THE VALUE OF p");
	scanf("%d",&p);
	printf("\nENTER THE VALUE OF n");
	scanf("%d",&n);

	printf("\nENTER THE VALUE OF r");
	scanf("%f",&r);*/

	si=0.0001;

      //
   //  printf("\nSIMPLE INTEREST=%f",si);

     // printf("\nSIMPLE INTEREST=%f",si);
      printf("%f",si);
      getch();

		}